import type { Character } from "./faces";

/** The starting cast, all original designs: an emoji, a demon mask, a cat, a big-eared creature, a robot, a pirate skull, a wizard owl and a small dragon. */
export const FACES: readonly Character[] = [
  {
    name: "Moji",
    field: ["#141040", "#2a1060"],
    head: "round",
    skin: "#ffd23f",
    shade: "#f0a020",
    eyes: "oval",
    eye: "#2a1a10",
    extras: [],
  },
  {
    name: "Oni",
    field: ["#200410", "#3a0818"],
    head: "mask",
    skin: "#e0303a",
    shade: "#901020",
    eyes: "fire",
    eye: "#ffb020",
    extras: ["horns"],
    tusks: true,
  },
  {
    name: "Mochi",
    field: ["#101838", "#1c2a58"],
    head: "round",
    skin: "#f4f1ff",
    shade: "#c8c0e8",
    eyes: "cat",
    eye: "#40c8a0",
    extras: ["ears"],
    whiskers: true,
    cheeks: "#ff9ac8",
  },
  {
    name: "Pip",
    field: ["#0c2030", "#103a40"],
    head: "round",
    skin: "#8fe3a0",
    shade: "#4fb070",
    eyes: "big",
    eye: "#102030",
    extras: ["bigears"],
    cheeks: "#ffe040",
  },
  {
    name: "Bolt",
    field: ["#06121c", "#0c2232"],
    head: "box",
    skin: "#3a4a68",
    shade: "#202a40",
    eyes: "scan",
    eye: "#40f0ff",
    extras: ["antenna"],
  },
  {
    name: "Captain",
    field: ["#0c0c18", "#20142c"],
    head: "skull",
    skin: "#f0ead8",
    shade: "#b8b0a0",
    eyes: "patch",
    eye: "#ff4040",
    extras: ["tricorn"],
  },
  {
    name: "Sage",
    field: ["#100c28", "#20184a"],
    head: "disc",
    skin: "#a87848",
    shade: "#6a4828",
    eyes: "owl",
    eye: "#ffb830",
    extras: ["wizard"],
  },
  {
    name: "Ember",
    field: ["#1c0c08", "#381808"],
    head: "round",
    skin: "#3fbf7f",
    shade: "#1f7f4f",
    eyes: "slit",
    eye: "#ffd040",
    extras: ["crest"],
    snout: true,
  },
];
